image: Visual Studio 2015
#clone_folder: D:\VScode_projects\GtestAndAppveyor
#clone_folder: C:\projects\gtestandappveyor
install:
- set PATH=c:\MinGW\bin;%PATH%
#- set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
build_script:
- cmd: >-
    echo %PATH%

    mkdir build

    cd build

    cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
    
    cmake --build .
#where gcc   
#cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
#cmake -G "MinGW Makefiles" -DCMAKE_IGNORE_PATH="C:/Program Files/Git/usr/bin" .. && mingw32-make