image: Visual Studio 2015
clone_folder: C:\projects\gtestandappveyor
install:
- set PATH=c:\msys64\mingw64\bin;%PATH%
build_script:
- cmd: >-
    echo %PATH%

    git submodule update --init --recursive
    
    mkdir build

    cd build

    cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..

    cmake --build .
test_script:
    - '%APPVEYOR_BUILD_FOLDER%\build\runTests.exe'