image: Visual Studio 2015
#clone_folder: D:\VScode_projects\GtestAndAppveyor
clone_folder: D:\vscode_projects\gtestandappveyor
build_script:
- cmd: >-
    mkdir build

    cd build

    cmake -G "MinGW Makefiles"  ..
    
    cmake --build .
#cmake -G "MinGW Makefiles" -DCMAKE_SH=SH-NOTFOUND ..