image: Visual Studio 2015
#clone_folder: D:\VScode_projects\GtestAndAppveyor
build_script:
- cmd: >-
    mkdir build

    cd build

    cmake -G "MinGW Makefiles" -DCMAKE_SH=SH-NOTFOUND ..
    
    cmake --build .
